export const AGE_UP = 'AGE_UP'
export const AGE_DOWN = 'AGE_DOWN'

export const SET_COURSE = 'SET_COURSE'
export const SET_ACTIVE_LESSON = 'SET_ACTIVE_LESSON'
export const SET_ACTIVE_OBJECT = 'SET_ACTIVE_OBJECT'
export const SET_ACTIVE_VIDEO = 'SET_ACTIVE_VIDEO'
export const MARK_DONE = 'MARK_DONE'
export const MARK_NOT_DOING = 'MARK_NOT_DOING'
export const MARK_NEXT_CLASS = 'MARK_NEXT_CLASS'